# Generated by Django 5.0.7 on 2024-11-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrollment_code',
            field=models.CharField(default='RCTt9AwDjx', max_length=10, unique=True),
        ),
    ]
