# Generated by Django 5.0.7 on 2024-11-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['due_date']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='lesson',
        ),
    ]
