# Generated by Django 5.0.7 on 2024-11-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='unique_code',
        ),
    ]
