# Generated by Django 5.0.7 on 2024-11-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_group_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
