# Generated by Django 5.0.7 on 2024-11-02 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
        ),
    ]
