import { Routes } from '@angular/router';
import { EditEmailComponent } from './edit-email/edit-email.component';
import { EditPasswordComponent } from './edit-password/edit-password.component';
import { EditPointComponent } from './edit-point/edit-point.component';
import { GroupChatComponent } from './group-chat/group-chat.component';
import { HelpCHComponent } from './help-c-h/help-c-h.component';
import { HomeComponent } from './home/home.component';
import { LmsForItComponent } from './lms-for-it/lms-for-it.component';
import { LoginInComponent } from './login-in/login-in.component';
import { ResetEmailComponent } from './reset-email/reset-email.component';
import { ResetPasswordComponent } from './reset-password/reset-password.component';
import { Sign_InComponent } from './sign-in/sign-in.component';
import { TeacherChatComponent } from './teacher-chat/teacher-chat.component';
import { TeacherLoginComponent } from './teacher-login/teacher-login.component';
import { TeacherPointAddAndEditComponent } from './teacher-point-add-and-edit/teacher-point-add-and-edit.component';
import { TeacherSignInComponent } from './teacher-sign-in/teacher-sign-in.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'edit_email', component: EditEmailComponent },
  { path: 'edit_password', component: EditPasswordComponent },
  { path: 'edit_point', component: EditPointComponent },
  { path: 'group_chat', component: GroupChatComponent },
  { path: 'help_c_h', component: HelpCHComponent },
  { path: 'home', component: HomeComponent },
  { path: 'lms_for_it', component: LmsForItComponent },
  { path: 'login_in', component: LoginInComponent },
  { path: 'reset_email', component: ResetEmailComponent },
  { path: 'reset-password', component: ResetPasswordComponent },
  { path: 'sign_in', component: Sign_InComponent },
  { path: 'teacher_chat', component: TeacherChatComponent },
  { path: 'teacher_login', component: TeacherLoginComponent },
  { path: 'teacher_point_add_and_edit', component: TeacherPointAddAndEditComponent },
  { path: 'teacher_sign_in', component: TeacherSignInComponent },
];
