services:
  frontend:
    build:
      context: ./fronted-react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./fronted-react:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend/it_course_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/it_course_backend:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DOCKER: "true"

  db:
    image: postgres:13
    ports:
      - '5433:5432'
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
