services:
  frontend:
    build:
      context: ./fronted-react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./fronted-react:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend/it_course_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/it_course_backend:/app
    depends_on:
      - db
    env_file:
      - ./backend/it_course_backend/it_course_backend/.env

  db:
    image: postgres:13
    env_file:
      - ./backend/it_course_backend/it_course_backend/.env
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: it_cours
      POSTGRES_USER: unikuni122
      POSTGRES_PASSWORD: melop5678
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
