# Generated by Django 5.0.6 on 2024-07-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_in", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loginattempt",
            old_name="attempted_at",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="loginattempt",
            name="success",
        ),
    ]
