export { default as AuthPage } from "./auth/AuthPage";
export { default as NavBar } from "./navbar/NavBar";
export { default as Footer } from "./Footer";
export { default as CreateCourseModal } from "./modals/CreateCourseModal"
export { default as CreateHomeworkModal } from "./modals/CreateHomeworkModal"
export { default as CreateLessonModal } from "./modals/CreateLessonModal"
export { default as ProgressChart } from "./Dashboard/ProgressChart"
export { default as PopularCourseList } from "./Dashboard/PopularCourseList"
export { default as CourseCard } from "./Dashboard/CourseCard"
